name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variable
        run: echo "BUILD_DIR=./public" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Build static site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
    env:
      BUILD_DIR: './public'
